package com.classliu.greendao.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TEST_DATA4".
 */
@Entity
public class TestData4 {

    @Id(autoincrement = true)
    private Long id;
    private String reader;
    private String readerString;
    private Integer testInt;
    private Boolean testBoolean;

    @Generated
    public TestData4() {
    }

    public TestData4(Long id) {
        this.id = id;
    }

    @Generated
    public TestData4(Long id, String reader, String readerString, Integer testInt, Boolean testBoolean) {
        this.id = id;
        this.reader = reader;
        this.readerString = readerString;
        this.testInt = testInt;
        this.testBoolean = testBoolean;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getReader() {
        return reader;
    }

    public void setReader(String reader) {
        this.reader = reader;
    }

    public String getReaderString() {
        return readerString;
    }

    public void setReaderString(String readerString) {
        this.readerString = readerString;
    }

    public Integer getTestInt() {
        return testInt;
    }

    public void setTestInt(Integer testInt) {
        this.testInt = testInt;
    }

    public Boolean getTestBoolean() {
        return testBoolean;
    }

    public void setTestBoolean(Boolean testBoolean) {
        this.testBoolean = testBoolean;
    }

}
