package com.classliu.greendao.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TEST_DATA".
 */
@Entity
public class TestData {

    @Id(autoincrement = true)
    private Long id;
    private String reader;
    private Long testLong;
    private java.util.Date testDate;
    private Integer testInt;
    private Boolean testBoolean;
    private Integer creatId;

    @Generated
    public TestData() {
    }

    public TestData(Long id) {
        this.id = id;
    }

    @Generated
    public TestData(Long id, String reader, Long testLong, java.util.Date testDate, Integer testInt, Boolean testBoolean, Integer creatId) {
        this.id = id;
        this.reader = reader;
        this.testLong = testLong;
        this.testDate = testDate;
        this.testInt = testInt;
        this.testBoolean = testBoolean;
        this.creatId = creatId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getReader() {
        return reader;
    }

    public void setReader(String reader) {
        this.reader = reader;
    }

    public Long getTestLong() {
        return testLong;
    }

    public void setTestLong(Long testLong) {
        this.testLong = testLong;
    }

    public java.util.Date getTestDate() {
        return testDate;
    }

    public void setTestDate(java.util.Date testDate) {
        this.testDate = testDate;
    }

    public Integer getTestInt() {
        return testInt;
    }

    public void setTestInt(Integer testInt) {
        this.testInt = testInt;
    }

    public Boolean getTestBoolean() {
        return testBoolean;
    }

    public void setTestBoolean(Boolean testBoolean) {
        this.testBoolean = testBoolean;
    }

    public Integer getCreatId() {
        return creatId;
    }

    public void setCreatId(Integer creatId) {
        this.creatId = creatId;
    }

    @Override
    public boolean equals(Object o) {
        return this.hashCode() == o.hashCode();
    }

    @Override
    public int hashCode() {
        return (id+reader).hashCode();
    }
}
